### ISSUE TITLE
misc character creation ui issues

### ISSUE THREAD

**Issue by misaacs21** [Roll-For-Init/Roll-For-Init#52]
no hover change on race/class icon cards
racial trait card tables not spaced correctly
racial trait cards should use read more/less
saving throw proficiencies are listed twice on class page
ability card container is too narrow
spells page container label font size too small
no indication of equipment card being "inactive" due to the other one being chosen; copy spells page styling for that

**Comment by seanpstanley** [comment]
added read more/less to racial trait cards 
fixed size of spell page label?
removed second instance of throws from class page
added zoom/background-color change on hover to race/class icon cards
fixed ability card container width
fixed racial trait card tables
indication of inactive cards tbd

**Comment by seanpstanley** [comment]
finished
